// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetailForecast.Data;

#nullable disable

namespace RetailForecast.Migrations
{
    [DbContext(typeof(RetailForecastDbContext))]
    partial class RetailForecastDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KpiTrainingRun", b =>
                {
                    b.Property<int>("FeaturesId")
                        .HasColumnType("integer")
                        .HasColumnName("features_id");

                    b.Property<int>("TrainingRunsId")
                        .HasColumnType("integer")
                        .HasColumnName("training_runs_id");

                    b.HasKey("FeaturesId", "TrainingRunsId")
                        .HasName("pk_training_run_features");

                    b.HasIndex("TrainingRunsId")
                        .HasDatabaseName("ix_training_run_features_training_runs_id");

                    b.ToTable("training_run_features", (string)null);
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StorageFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_file_path");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_datasets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_datasets_user_id");

                    b.ToTable("datasets", (string)null);
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Horizon")
                        .HasColumnType("integer")
                        .HasColumnName("horizon");

                    b.Property<int>("TrainingRunId")
                        .HasColumnType("integer")
                        .HasColumnName("training_run_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_forecasts");

                    b.HasIndex("TrainingRunId")
                        .HasDatabaseName("ix_forecasts_training_run_id");

                    b.ToTable("forecasts", (string)null);
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.ForecastValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("ForecastId")
                        .HasColumnType("integer")
                        .HasColumnName("forecast_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_forecast_values");

                    b.HasIndex("ForecastId")
                        .HasDatabaseName("ix_forecast_values_forecast_id");

                    b.ToTable("forecast_values", (string)null);
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Kpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_type");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_kpis");

                    b.HasIndex("DatasetId")
                        .HasDatabaseName("ix_kpis_dataset_id");

                    b.ToTable("kpis", (string)null);
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("algorithm");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.TrainingMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("TrainingRunId")
                        .HasColumnType("integer")
                        .HasColumnName("training_run_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_training_metrics");

                    b.HasIndex("TrainingRunId")
                        .HasDatabaseName("ix_training_metrics_training_run_id");

                    b.ToTable("training_metrics", (string)null);
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.TrainingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer")
                        .HasColumnName("dataset_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TargetColumn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target_column");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_training_runs");

                    b.HasIndex("DatasetId")
                        .HasDatabaseName("ix_training_runs_dataset_id");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_training_runs_model_id");

                    b.ToTable("training_runs", (string)null);
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KpiTrainingRun", b =>
                {
                    b.HasOne("RetailForecast.Domain.Entities.Kpi", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_training_run_features_kpis_features_id");

                    b.HasOne("RetailForecast.Domain.Entities.TrainingRun", null)
                        .WithMany()
                        .HasForeignKey("TrainingRunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_training_run_features_training_runs_training_runs_id");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Dataset", b =>
                {
                    b.HasOne("RetailForecast.Domain.Entities.User", "User")
                        .WithMany("Datasets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_datasets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Forecast", b =>
                {
                    b.HasOne("RetailForecast.Domain.Entities.TrainingRun", "TrainingRun")
                        .WithMany("Forecasts")
                        .HasForeignKey("TrainingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forecasts_training_runs_training_run_id");

                    b.Navigation("TrainingRun");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.ForecastValue", b =>
                {
                    b.HasOne("RetailForecast.Domain.Entities.Forecast", "Forecast")
                        .WithMany("ForecastValues")
                        .HasForeignKey("ForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forecast_values_forecasts_forecast_id");

                    b.Navigation("Forecast");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Kpi", b =>
                {
                    b.HasOne("RetailForecast.Domain.Entities.Dataset", "Dataset")
                        .WithMany("Kpis")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kpis_datasets_dataset_id");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.TrainingMetric", b =>
                {
                    b.HasOne("RetailForecast.Domain.Entities.TrainingRun", "TrainingRun")
                        .WithMany("Metrics")
                        .HasForeignKey("TrainingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_training_metrics_training_runs_training_run_id");

                    b.Navigation("TrainingRun");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.TrainingRun", b =>
                {
                    b.HasOne("RetailForecast.Domain.Entities.Dataset", "Dataset")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_training_runs_datasets_dataset_id");

                    b.HasOne("RetailForecast.Domain.Entities.Model", "Model")
                        .WithMany("TrainingRuns")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_runs_models_model_id");

                    b.Navigation("Dataset");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Dataset", b =>
                {
                    b.Navigation("Kpis");

                    b.Navigation("TrainingRuns");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Forecast", b =>
                {
                    b.Navigation("ForecastValues");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.Model", b =>
                {
                    b.Navigation("TrainingRuns");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.TrainingRun", b =>
                {
                    b.Navigation("Forecasts");

                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("RetailForecast.Domain.Entities.User", b =>
                {
                    b.Navigation("Datasets");
                });
#pragma warning restore 612, 618
        }
    }
}
